# Generated by Django 3.2.9 on 2021-11-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_active',
            new_name='isActive',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_change_date',
            new_name='lastChangeDate',
        ),
    ]
