# Generated by Django 3.2.9 on 2021-11-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0002_auto_20211118_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
